# Base configs
baseurl: "https://www.junderhill.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Jason Underhill"
subtitle: "See the world through my eyes!"
author: "Jason Underhill"
header:
 title: "Photography"
 subtitle: "by Jason Underhill"
footer:
 name: "Hey there, my name is Jason"
 bio: ""
 github: ""
web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/underhillj"
  instagram: "https://www.instagram.com/underhillj"
